name: Python CI

# Trigger the workflow on push or pull request events
on: 
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:

        # checkout the code form the repository
        - name: Checkout code
          uses: actions/checkout@v2

        # set up python environment
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.8'
        
        # install dependencies
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        
        # run unit tests
        - name: Run unit tests
          run: |
            python -m pytest tests/

